services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pico
      POSTGRES_USER: pico
      POSTGRES_PASSWORD: pico
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pico"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine

  backend:
    build:
      context: ./backend
    environment:
      DJANGO_SECRET_KEY: dee321f5-9492-4325-9943-b31e39c50924
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "*"
      DATABASE_URL: postgres://pico:pico@postgres:5432/pico
      REDIS_URL: redis://redis:6379/0
      CORS_ALLOWED_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
      CELERY_TASK_ALWAYS_EAGER: "0"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["/app/docker/entrypoint.sh"]

  celery:
    build:
      context: ./backend
    environment:
      DJANGO_SECRET_KEY: dee321f5-9492-4325-9943-b31e39c50924
      DJANGO_DEBUG: "1"
      DATABASE_URL: postgres://pico:pico@postgres:5432/pico
      REDIS_URL: redis://redis:6379/0
      CELERY_TASK_ALWAYS_EAGER: "0"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["celery", "-A", "config", "worker", "-l", "info"]

  celery-beat:
    build:
      context: ./backend
    environment:
      DJANGO_SECRET_KEY: dee321f5-9492-4325-9943-b31e39c50924
      DJANGO_DEBUG: "1"
      DATABASE_URL: postgres://pico:pico@postgres:5432/pico
      REDIS_URL: redis://redis:6379/0
      CELERY_TASK_ALWAYS_EAGER: "0"
    depends_on:
      postgres:
        condition: service_healthy
      backend:
        condition: service_started
      redis:
        condition: service_started
      celery:
        condition: service_started
      
    command: ["celery", "-A", "config", "beat", "-l", "info"]


  frontend:
    build:
      context: ./frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data1:
