import React from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, Navigate, Outlet, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { Activity, CreditCard, LayoutDashboard, LogOut, PackageOpen, Play, Server, Shield, Square, Trash2, UserCircle, type LucideIcon } from 'lucide-react';
import { adminDashboard, createVm, customerDashboard, deleteVm, listAudit, listCustomers, listInvoices, listPackages, listVms, login, me, payInvoice, register, vmAction, type Invoice, type Vm } from './api';

function useMe() { return useQuery({ queryKey: ['me'], queryFn: me, retry: false }); }
function StatusPill({ value }: { value: string }) { const tone = value === 'ACTIVE' || value === 'PAID' ? 'bg-emerald-100 text-emerald-800' : value === 'PENDING' || value === 'PROVISIONING' ? 'bg-amber-100 text-amber-800' : 'bg-slate-100 text-slate-700'; return <span className={`rounded px-2 py-1 text-xs font-semibold ${tone}`}>{value}</span>; }
function Money({ value }: { value: string }) { return <span>${Number(value).toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>; }
function Empty({ title }: { title: string }) { return <div className="border border-dashed border-line bg-white p-8 text-center text-sm text-slate-500">{title}</div>; }
function Spinner() { return <div className="p-6 text-sm text-slate-500">Loading...</div>; }
function ErrorBox({ message = 'Something went wrong.' }: { message?: string }) { return <div className="border border-red-200 bg-red-50 p-4 text-sm text-red-700">{message}</div>; }

function AuthPage({ mode }: { mode: 'login' | 'register' }) {
  const navigate = useNavigate(); const qc = useQueryClient();
  const mutation = useMutation({ mutationFn: async (form: FormData) => mode === 'login' ? login(String(form.get('email')), String(form.get('password'))) : register(String(form.get('email')), String(form.get('password')), String(form.get('company'))), onSuccess: async (data) => { if (data.access) localStorage.setItem('accessToken', data.access); if (mode === 'register') { const tokens = await login(String(document.querySelector<HTMLInputElement>('#email')?.value), String(document.querySelector<HTMLInputElement>('#password')?.value)); localStorage.setItem('accessToken', tokens.access); } await qc.invalidateQueries({ queryKey: ['me'] }); navigate('/'); } });
  return <main className="grid min-h-screen place-items-center bg-[#edf2f5] px-4"><section className="w-full max-w-md border border-line bg-white p-8 shadow-sm"><h1 className="text-2xl font-semibold">PICO Self-Service Cloud Portal</h1><p className="mt-2 text-sm text-slate-600">{mode === 'login' ? 'Sign in to manage cloud resources.' : 'Create a customer account.'}</p><form className="mt-6 space-y-4" onSubmit={(e) => { e.preventDefault(); mutation.mutate(new FormData(e.currentTarget)); }}><input id="email" name="email" type="email" required placeholder="Email" className="focus-ring w-full border border-line px-3 py-2" />{mode === 'register' && <input name="company" required placeholder="Company name" className="focus-ring w-full border border-line px-3 py-2" />}<input id="password" name="password" type="password" required placeholder="Password" className="focus-ring w-full border border-line px-3 py-2" />{mutation.isError && <ErrorBox message="Authentication failed. Check the details and try again." />}<button className="focus-ring w-full bg-brand px-4 py-2 font-semibold text-white" disabled={mutation.isPending}>{mutation.isPending ? 'Working...' : mode === 'login' ? 'Login' : 'Register'}</button></form><Link className="mt-4 block text-sm text-brand" to={mode === 'login' ? '/register' : '/login'}>{mode === 'login' ? 'Create an account' : 'Already have an account'}</Link></section></main>;
}

type NavItem = readonly [string, string, LucideIcon];
function Layout() { const { data: user, isLoading, isError } = useMe(); const nav = useNavigate(); if (isLoading) return <Spinner />; if (isError || !user) return <Navigate to="/login" replace />; const items: NavItem[] = user.role === 'ADMIN' ? [['/admin','Dashboard',Shield],['/admin/customers','Customers',UserCircle],['/admin/resources','Resources',Server],['/admin/invoices','Invoices',CreditCard]] : [['/','Dashboard',LayoutDashboard],['/catalog','Catalog',PackageOpen],['/resources','Resources',Server],['/invoices','Invoices',CreditCard],['/audit','Audit',Activity],['/profile','Profile',UserCircle]]; return <div className="min-h-screen bg-[#f6f8fa]"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-line bg-white p-4 md:block"><div className="mb-6 text-lg font-semibold">PICO Portal</div><nav className="space-y-1">{items.map(([to,label,Icon]) => <Link key={to} to={to} className="flex items-center gap-3 px-3 py-2 text-sm hover:bg-slate-100"><Icon size={18}/>{label}</Link>)}</nav></aside><header className="border-b border-line bg-white p-4 md:ml-64"><div className="flex items-center justify-between"><div><div className="font-semibold">{user.company_name || user.email}</div><div className="text-xs text-slate-500">{user.role}</div></div><button className="focus-ring flex items-center gap-2 border border-line px-3 py-2 text-sm" onClick={() => { localStorage.removeItem('accessToken'); nav('/login'); }}><LogOut size={16}/>Logout</button></div></header><main className="p-4 md:ml-64 md:p-6"><Outlet /></main></div>; }

function Dashboard() { const q = useQuery({ queryKey:['dashboard'], queryFn: customerDashboard }); if (q.isLoading) return <Spinner/>; if (q.isError) return <ErrorBox/>; return <section><h2 className="mb-4 text-xl font-semibold">Dashboard</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(q.data).map(([k,v]) => <div key={k} className="border border-line bg-white p-4"><div className="text-sm text-slate-500">{k.replaceAll('_',' ')}</div><div className="mt-2 text-2xl font-semibold">{String(v)}</div></div>)}</div></section>; }
function Catalog() { const q = useQuery({ queryKey:['packages'], queryFn:listPackages }); const qc=useQueryClient(); const m=useMutation({ mutationFn:createVm, onSuccess:()=>qc.invalidateQueries({queryKey:['vms']}) }); if(q.isLoading)return <Spinner/>; return <section><h2 className="mb-4 text-xl font-semibold">Catalog</h2>{m.isSuccess && <div className="mb-4 border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">VM provisioning requested.</div>}<div className="grid gap-4 lg:grid-cols-3">{q.data?.map(pkg=><div key={pkg.id} className="border border-line bg-white p-5"><h3 className="text-lg font-semibold">{pkg.name}</h3><div className="mt-3 text-sm text-slate-600">{pkg.vcpu} vCPU · {pkg.ram_mb/1024} GB RAM · {pkg.disk_gb} GB disk</div><div className="mt-4 text-2xl font-semibold"><Money value={pkg.monthly_price}/><span className="text-sm font-normal text-slate-500"> / month</span></div><form className="mt-4 flex gap-2" onSubmit={(e)=>{e.preventDefault(); const name=new FormData(e.currentTarget).get('name') as string; m.mutate({name, package_id:pkg.id});}}><input name="name" required placeholder="vm-name" className="focus-ring min-w-0 flex-1 border border-line px-3 py-2 text-sm"/><button className="focus-ring bg-brand px-3 py-2 text-sm font-semibold text-white">Provision</button></form></div>)}</div></section>; }
function Resources() { const q=useQuery({queryKey:['vms'], queryFn:listVms}); const qc=useQueryClient(); const act=useMutation({mutationFn:({id,action}:{id:number;action:'start'|'stop'})=>vmAction(id,action), onSuccess:()=>qc.invalidateQueries({queryKey:['vms']})}); const del=useMutation({mutationFn:deleteVm,onSuccess:()=>qc.invalidateQueries({queryKey:['vms']})}); if(q.isLoading)return <Spinner/>; if(!q.data?.length)return <Empty title="No virtual machines yet."/>; return <Table headers={['Name','Package','Status','IP','Actions']}>{q.data.map(vm=><tr key={vm.id}><td><Link className="text-brand" to={`/resources/${vm.id}`}>{vm.name}</Link></td><td>{vm.package.name}</td><td><StatusPill value={vm.status}/></td><td>{vm.ip_address || '-'}</td><td className="flex gap-2"><button title="Start" onClick={()=>act.mutate({id:vm.id,action:'start'})}><Play size={16}/></button><button title="Stop" onClick={()=>act.mutate({id:vm.id,action:'stop'})}><Square size={16}/></button><button title="Delete" onClick={()=>del.mutate(vm.id)}><Trash2 size={16}/></button></td></tr>)}</Table>; }
function VmDetails(){ const {id}=useParams(); const vms=useQuery({queryKey:['vms'],queryFn:listVms}); const invoices=useQuery({queryKey:['invoices'],queryFn:listInvoices}); const audit=useQuery({queryKey:['audit'],queryFn:listAudit}); if(vms.isLoading)return <Spinner/>; const vm=vms.data?.find(v=>String(v.id)===id); if(!vm)return <ErrorBox message="VM not found."/>; const inv=invoices.data?.find(i=>i.vm===vm.id); const events=audit.data?.filter(a=>a.entity_type==='vm'&&a.entity_id===String(vm.id)); return <section className="grid gap-4 lg:grid-cols-[1fr_360px]"><div className="border border-line bg-white p-5"><h2 className="text-xl font-semibold">{vm.name}</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><dt>Package</dt><dd>{vm.package.name}</dd><dt>Status</dt><dd><StatusPill value={vm.status}/></dd><dt>IP</dt><dd>{vm.ip_address || '-'}</dd><dt>Created</dt><dd>{new Date(vm.created_at).toLocaleString()}</dd><dt>Invoice</dt><dd>{inv ? `${inv.invoice_number} (${inv.status})` : '-'}</dd></dl></div><Timeline logs={events || []}/></section>; }
function Invoices(){ const q=useQuery({queryKey:['invoices'],queryFn:listInvoices}); const qc=useQueryClient(); const pay=useMutation({mutationFn:payInvoice,onSuccess:()=>qc.invalidateQueries({queryKey:['invoices']})}); if(q.isLoading)return <Spinner/>; if(!q.data?.length)return <Empty title="No invoices yet."/>; return <Table headers={['Number','VM','Amount','Due','Status','Action']}>{q.data.map(i=><tr key={i.id}><td>{i.invoice_number}</td><td>{i.vm_name}</td><td><Money value={i.amount}/></td><td>{i.due_date}</td><td><StatusPill value={i.status}/></td><td>{i.status!=='PAID' && <button className="bg-brand px-3 py-1 text-sm text-white" onClick={()=>pay.mutate(i.id)}>Pay</button>}</td></tr>)}</Table>; }
function Audit(){ const q=useQuery({queryKey:['audit'],queryFn:listAudit}); if(q.isLoading)return <Spinner/>; return <Timeline logs={q.data || []}/>; }
function Timeline({logs}:{logs:{id:number;action:string;description:string;created_at:string}[]}){ if(!logs.length)return <Empty title="No audit events."/>; return <div className="border border-line bg-white p-5"><h3 className="mb-4 font-semibold">Audit Timeline</h3><ol className="space-y-4">{logs.map(l=><li key={l.id} className="border-l-2 border-brand pl-3"><div className="text-sm font-semibold">{l.action.replaceAll('_',' ')}</div><div className="text-sm text-slate-600">{l.description}</div><div className="text-xs text-slate-400">{new Date(l.created_at).toLocaleString()}</div></li>)}</ol></div>; }
function Profile(){ const q=useMe(); return <section className="border border-line bg-white p-5"><h2 className="text-xl font-semibold">Profile</h2><p className="mt-4 text-sm">{q.data?.email}</p><p className="text-sm text-slate-600">{q.data?.company_name}</p></section>; }
function AdminDashboard(){ const q=useQuery({queryKey:['admin-dashboard'],queryFn:adminDashboard}); if(q.isLoading)return <Spinner/>; return <DashboardGrid data={q.data}/>; }
function DashboardGrid({data}:{data:Record<string,unknown>}){ return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(data).map(([k,v])=><div className="border border-line bg-white p-4" key={k}><div className="text-xs text-slate-500">{k.replaceAll('_',' ')}</div><div className="mt-2 text-2xl font-semibold">{String(v)}</div></div>)}</div>; }
function Customers(){ const q=useQuery({queryKey:['customers'],queryFn:listCustomers}); if(q.isLoading)return <Spinner/>; return <Table headers={['Company','Email','Created']}>{q.data?.map(c=><tr key={c.id}><td>{c.company_name}</td><td>{c.email}</td><td>{new Date(c.created_at).toLocaleDateString()}</td></tr>)}</Table>; }
function Table({headers,children}:{headers:string[];children:React.ReactNode}){ return <div className="overflow-x-auto border border-line bg-white"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-100 text-slate-600"><tr>{headers.map(h=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-line [&_td]:px-4 [&_td]:py-3">{children}</tbody></table></div>; }
function AdminInvoices(){ return <Invoices/>; }
function AdminResources(){ return <Resources/>; }
function RequireAnon({children}:{children:React.ReactNode}){ return localStorage.getItem('accessToken') ? <Navigate to="/" replace/> : <>{children}</>; }

export default function App(){ return <Routes><Route path="/login" element={<RequireAnon><AuthPage mode="login"/></RequireAnon>}/><Route path="/register" element={<RequireAnon><AuthPage mode="register"/></RequireAnon>}/><Route element={<Layout/>}><Route index element={<Dashboard/>}/><Route path="catalog" element={<Catalog/>}/><Route path="resources" element={<Resources/>}/><Route path="resources/:id" element={<VmDetails/>}/><Route path="invoices" element={<Invoices/>}/><Route path="audit" element={<Audit/>}/><Route path="profile" element={<Profile/>}/><Route path="admin" element={<AdminDashboard/>}/><Route path="admin/customers" element={<Customers/>}/><Route path="admin/resources" element={<AdminResources/>}/><Route path="admin/invoices" element={<AdminInvoices/>}/></Route></Routes>; }
